// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRkB1uKUYdjkjJU3O51sS26pspoUJwX9Y',
    appId: '1:797205751956:web:380a86c0dbeb12be84ec81',
    messagingSenderId: '797205751956',
    projectId: 'ten-to-twelve',
    authDomain: 'ten-to-twelve.firebaseapp.com',
    storageBucket: 'ten-to-twelve.appspot.com',
    measurementId: 'G-5T8CEM95EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7FtxV0llOMezL4G3YglVKct6R8ULny2Q',
    appId: '1:797205751956:android:97f73adc7473b2a784ec81',
    messagingSenderId: '797205751956',
    projectId: 'ten-to-twelve',
    storageBucket: 'ten-to-twelve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjClD0K9jP_2XpMQ1bQXB0xZ6nlvD25lE',
    appId: '1:797205751956:ios:eb5b5723450bfdf084ec81',
    messagingSenderId: '797205751956',
    projectId: 'ten-to-twelve',
    storageBucket: 'ten-to-twelve.appspot.com',
    iosClientId: '797205751956-8qatob1u6bj0huesgr7jmsh4pp73ms0e.apps.googleusercontent.com',
    iosBundleId: 'com.app.firebaseTen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjClD0K9jP_2XpMQ1bQXB0xZ6nlvD25lE',
    appId: '1:797205751956:ios:eb5b5723450bfdf084ec81',
    messagingSenderId: '797205751956',
    projectId: 'ten-to-twelve',
    storageBucket: 'ten-to-twelve.appspot.com',
    iosClientId: '797205751956-8qatob1u6bj0huesgr7jmsh4pp73ms0e.apps.googleusercontent.com',
    iosBundleId: 'com.app.firebaseTen',
  );
}
